[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/translate/*"
  to = "https://fanyi-api.baidu.com/api/trans/vip/translate/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/youdao"
  to = "/.netlify/functions/youdao-proxy"
  status = 200


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/baidu-proxy"
  status = 200